### ISSUE TITLE
Output file does not opening with UABE 3.0 beta 1

### ISSUE THREAD

**Issue by Fr567ujnbv** [Fr567ujnbv/UXORBreaker#1]
I've tested the resulting output file on a few tools and the output result doesn't directly open with UABE 3.0 beta 1. It will however open in UABE 2.2. UABE 3.0 will open the file that 2.2 saves when uncompressing. I suspect this is an issue with UABE not being compatible with files that have uncompressed metadata.

**Comment by DarthShader** [comment]
UABE seems to be an outdated & abandoned project. You're probably better off using the final releases of AssetStudio, uTinyRipper, or the latest release of AssetRipper.

**Comment by Fr567ujnbv** [comment]
The compatibility issue seems to be with UABE and is out of scope of this project to fix.
